### ISSUE TITLE
QtWebEngine ?

### ISSUE THREAD

**Issue by stonebig** [Anaconda-Server/nbbrowserpdf#7]
Hi, small question.

nbbrowserpdf is currently relying on Qt Webkit 

Will it work automatically with the new Qt WebEngine ?

currently I have a "Ghost requires PyQt4 or Pyside" , so I'm lost with my maintained PyQt5

**Comment by bollwyvl** [comment]
Yeah, that's the brakes on dependencies of this scale.

PyQt5 support has been put forward for [ghost.py](https://github.com/jeanphix/Ghost.py/pull/205), but that hasn't been merged yet..

We could possible do without ghost.py (but it is quite convenient for encapsulating the different dependencies, etc) but neither pyqt5 or pyside2 is fully operational with QtWebEngine yet: please correct me if I'm wrong! I'll be monitoring developments in those spaces, but don't have the bandwidth to really get my hands dirty there.

**Comment by stonebig** [comment]
also, the "best for winpython" install option is:
`python -m nbbrowserpdf.install --user`

This is what I use for bqplot, I just forgot this "--user".

**Comment by stonebig** [comment]
QtWebEngine may arrive on Windows with PyQt5.6 and if you are Python 3.5, loosing Webkit at the same time.
==> I may expect that PyQt5.6 is going to be a february 2016 event.

**Comment by bollwyvl** [comment]
> QtWebEngine may arrive on Windows with PyQt5.6 and if you are Python 3.5, loosing Webkit at the same time.

Right: I'll be monitoring the situation

> I may guess-estimate that PyQt5.6 is going to be a february 2016 event. I just hope that nbbrowserpdf will support QtWebEngine at that moment.

Well, we're going to be shooting for a pretty large matrix of supported environments, so _at that moment_ may be a bit of a stretch!

> also, the "best for winpython" install option is:
> python -m nbbrowserpdf.install --user

Great! please feel free to close up that other issue, as I think all of the documentation is pretty consistent across the projects to get the behaviour you are after.

**Comment by bollwyvl** [comment]
I've set up a google alert for "pyqt QtWebEngine", will update as I hear things. But for now, closing.
