### ISSUE TITLE
 `nbextensions` placement may not be correct

### ISSUE THREAD

**Issue by stonebig** [Anaconda-Server/nbbrowserpdf#8]
If I'm correct (the `truth`may have evolved on the subject (but bqplot, and ipyparallell let me believe so):
- if I have `JUPYTER_DATA_DIR=D:\WinPython\basedir34\buildQt5\winpython-3.4.3.amd64\settings`
- then nbextensions should be installed at `D:\WinPython\basedir34\buildQt5\winpython-3.4.3.amd64\settings\nbextensions\nbbrowserpdf`

This is currently not the case
````
D:\WinPython\basedir34\buildQt5\winpython-3.4.3.amd64\python-3.4.3.amd64>python
-m nbbrowserpdf.install
copying D:\WinPython\basedir34\buildQt5\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\nbbrowserpdf\static\nbbrowserpdf\index.js -> C:\ProgramData\j
upyter\nbextensions\nbbrowserpdf\index.js
````
I may be wrong, so you may check with experts / do-ers for this.

**Comment by bollwyvl** [comment]
Thanks for the feedback. We're working through a number of these issues related to different kinds of installation/usage scenarios.

The [default behavior](https://github.com/jupyter/notebook/blob/master/notebook/nbextensions.py#L63) of `nbextension install` is (weirdly) the cross-user `global` installation. passing in:
```
python -m nbbrowserpdf.install --user
```

would force it to the more broadly-adopted `$HOME/.jupyter`, or rather in your custom location.

Looks like this is also the [guidance on bqplot](https://github.com/bloomberg/bqplot#installation).

And if you always want it to load, use `--enable`, as well!

**Comment by stonebig** [comment]
oups! my bad, the `--user` option I did forget. so issue closed if you already accept that option
